--Create util user:
CREATE USER sec_admin IDENTIFIED BY oracle ACCOUNT UNLOCK;

--Grants:
GRANT CONNECT, CREATE SESSION, RESOURCE TO sec_admin;

GRANT CREATE PROCEDURE TO sec_admin;

GRANT CREATE ANY CONTEXT TO sec_admin;

GRANT EXECUTE ON DBMS_RLS TO sec_admin;

GRANT CREATE PUBLIC SYNONYM TO sec_admin;

GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW TO sec_admin;

GRANT CREATE SEQUENCE TO sec_admin;

GRANT EXECUTE ON SYS.DBMS_SESSION TO sec_admin;

GRANT SELECT_CATALOG_ROLE, SELECT ANY DICTIONARY TO sec_admin;

GRANT UNLIMITED TABLESPACE TO sec_admin;

GRANT DROP PUBLIC SYNONYM TO sec_admin;

GRANT CREATE ANY TRIGGER TO sec_admin;

GRANT ADMINISTER DATABASE TRIGGER TO sec_admin;




